### ISSUE TITLE
Getting ModuleNotFoundError: No module named 'library_management' after install

### ISSUE THREAD

**Issue by Ghousepasha-ios** [frappe/library_management#8]
I Installed library_management in frappe docker with below commands.

bench get-app https://github.com/frappe/library_management.git
bench --site frappe.localhost install-app library_management

After i restart the docker images, am getting following images Restarting always 
<img width="638" alt="Screen Shot 2021-06-21 at 11 29 35 AM" src="https://user-images.githubusercontent.com/2462284/122731424-f7826a00-d283-11eb-9dc1-c2a739e25afd.png">

When i check the logs i found below error.
Attempt 1 to connect to mariadb:3306
Attempt 1 to connect to redis-queue:6379
Attempt 1 to connect to redis-cache:6379
Attempt 1 to connect to redis-socketio:6379
Connections OK
`Traceback (most recent call last):
  File "/home/frappe/frappe-bench/commands/worker.py", line 12, in <module>
    main()
  File "/home/frappe/frappe-bench/commands/worker.py", line 7, in main
    start_worker(queue, False)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 139, in start_worker
    with frappe.init_site():
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 287, in __enter__
    init(self.site)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 208, in init
    setup_module_map()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1113, in setup_module_map
    for module in get_module_list(app):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 981, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in get_module
    return importlib.import_module(modulename)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'library_management'`
can you please let me know how to fix it.

**Comment by tienhm0202** [comment]
This repo is paused 8 years ago, I don't think it will work with frappe's latest version
